export const fakeDataProducts = {
  state: "OK",
  data: {
    data: [
      {
        code: "0102",
        title: "FORTIKIDS BEBIDA SABORIZ CHOCO 180ML",
        price: "1502",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "1",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/0102.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "BOLSA",
        },
      },
      {
        code: "0112",
        title: "FORTIKIDS CHOCOLECHEX10",
        price: "15021",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "5",
        combo: "false",
        weight: "2",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/0112.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "BOLSA",
        },
      },
      {
        code: "7014",
        title: "KD CEREAL AZUCARADO 120G",
        price: "1580",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7014.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "POTE",
        },
      },
      {
        code: "7015",
        title: "KD CEREAL CHOCOARROZ 120G",
        price: "1580",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7015.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "POTE",
        },
      },
      {
        code: "7017",
        title: "KD CEREAL 120GX6 AZ-CH",
        price: "9481",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "1",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7017.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "POTE",
        },
      },
      {
        code: "7378",
        title: "ACTIGEST VAS 140G PIT CCB",
        price: "1796",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7378.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "7379",
        title: "ACTIGEST VAS 140G PIT CCB TT",
        price: "1796",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7379.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "7393",
        title: "ACTIGEST BOT 1750G PITAYA",
        price: "14723",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "2",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7393.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "BOTELLA",
        },
      },
      {
        code: "7407",
        title: "ACTIGEST CUCH 100GX12 FRE-PIT REG",
        price: "13076",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "1",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7407.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "POTE",
        },
      },
      {
        code: "7419",
        title: "ALQUERÍA OREO 100GR",
        price: "2083",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7419.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "7424",
        title: "ALQUERIA OREO X2100GR",
        price: "4166",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7424.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "7436",
        title: "ALQUERÍA OREO X4 100GR",
        price: "8044",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7436.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "7550",
        title: "ALQUERIA M&M 100G",
        price: "2083",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7550.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "7552",
        title: "ALQUERIA M&M 2 X100G",
        price: "4166",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7552.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "7553",
        title: "ALQUERIA M&M 4 X100G",
        price: "8044",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7553.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "7606",
        title: "KD CUCH 95GX12 FRE-MOR",
        price: "9908",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "1",
        categories: "8",
        sub_categories: "8",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7606.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "8",
          subcategoria: "8",
          sublinea: "8",
          linea: "8",
          embalaje: "POTE",
        },
      },
      {
        code: "7607",
        title: "KD CUCH 95G FRESA",
        price: "933",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "8",
        sub_categories: "8",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7607.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "8",
          subcategoria: "8",
          sublinea: "8",
          linea: "8",
          embalaje: "POTE",
        },
      },
      {
        code: "7608",
        title: "KD CUCH 95G MORA",
        price: "933",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "8",
        sub_categories: "8",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7608.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "8",
          subcategoria: "8",
          sublinea: "8",
          linea: "8",
          embalaje: "POTE",
        },
      },
      {
        code: "7640",
        title: "KD BOL 150GX6 FR-MO",
        price: "5605",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "1",
        categories: "8",
        sub_categories: "8",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7640.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "8",
          subcategoria: "8",
          sublinea: "8",
          linea: "8",
          embalaje: "BOLSA",
        },
      },
      {
        code: "7646",
        title: "KD BOL 150G MORA",
        price: "933",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "8",
        sub_categories: "8",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7646.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "8",
          subcategoria: "8",
          sublinea: "8",
          linea: "8",
          embalaje: "BOLSA",
        },
      },
      {
        code: "7652",
        title: "KD GELATINA 90GX4 CEREZA",
        price: "4311",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7652.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "POTE",
        },
      },
      {
        code: "7653",
        title: "KD GELATINA 90GX4 NARANJA",
        price: "4311",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7653.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "POTE",
        },
      },
      {
        code: "7654",
        title: "KD GELATINA 90G CEREZA",
        price: "1076",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7654.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "POTE",
        },
      },
      {
        code: "7655",
        title: "KD GELATINA 90G NARANJA",
        price: "1076",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7655.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "POTE",
        },
      },
      {
        code: "7657",
        title: "YOGURT KD VAS NIÑOS 150G X 6",
        price: "10558",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "1",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7657.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO PITILLO",
        },
      },
      {
        code: "7658",
        title: "YOGURT KD VASO NIÑOS 150 FRE",
        price: "1796",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7658.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO PITILLO",
        },
      },
      {
        code: "7659",
        title: "YOGURT KD VAS NIÑOS 150G MEL",
        price: "1796",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7659.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO PITILLO",
        },
      },
      {
        code: "7660",
        title: "YOGURT KD VAS NIÑOS 150G MOR",
        price: "1796",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7660.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO PITILLO",
        },
      },
      {
        code: "7689",
        title: "ALIMENTO LACTEO KD TRULULU",
        price: "2083",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7689.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "7690",
        title: "ALIMENTO LACTEO KD TRULULU X2",
        price: "4166",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7690.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "7691",
        title: "ALIMENTO LACTEO KD TRULULU X4",
        price: "8044",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7691.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "7724",
        title: "KD GELATINA 90G SANDIA FRESA",
        price: "1076",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7724.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "POTE",
        },
      },
      {
        code: "7725",
        title: "KD GELATINA 90GX4 SANDIA FRESA",
        price: "4311",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7725.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "POTE",
        },
      },
      {
        code: "7772",
        title: "YOGURT ALQ VASO 150G SABOR COL FRESA",
        price: "1751",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7772.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "7773",
        title: "YOGURT ALQ VASO 150G SABOR COL MELO",
        price: "1751",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7773.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "7774",
        title: "YOGURT ALQ VASO 150G SABOR COL MORA",
        price: "1751",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7774.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "7776",
        title: "ALQUERIA CER 170G FLIPS",
        price: "2729",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7776.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "7777",
        title: "ALQUERIA CER 170G FLIPS- HOJUELAS X3",
        price: "8188",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "1",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7777.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "7779",
        title: "ALQUERÍA HOJUELAS 170GR",
        price: "2729",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7779.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "7780",
        title: "ALQUERIA MILO 170GR",
        price: "2729",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7780.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "7792",
        title: "ALQ HOJUELAS PACK X3",
        price: "8188",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "1",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/7792.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "D011",
        title: "KD BOL 150GX6 FR-MEL",
        price: "5605",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "1",
        categories: "8",
        sub_categories: "8",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/D011.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "8",
          subcategoria: "8",
          sublinea: "8",
          linea: "8",
          embalaje: "BOLSA",
        },
      },
      {
        code: "D013",
        title: "YOGURT ALQUERIA PACKX3 SURTIDO",
        price: "5253",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/D013.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "D014",
        title: "KD BOL 150G MELOCOTON",
        price: "933",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/D014.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "BOLSA",
        },
      },
      {
        code: "D039",
        title: "CUCHAREABLE ALQUERIA MELOC 4X100G",
        price: "4311",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/D039.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "POTE",
        },
      },
      {
        code: "D040",
        title: "CUCHAREABLE ALQUERIA 6X100G FR-ME",
        price: "6899",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "1",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/D040.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "D041",
        title: "CUCHAREABLE ALQUERIA FRESA 4X100G",
        price: "4311",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/D041.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "D043",
        title: "CUCHAREABLE ALQUERIA 100G FRESA",
        price: "1151",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "7",
        sub_categories: "7",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/D043.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "7",
          subcategoria: "7",
          sublinea: "7",
          linea: "7",
          embalaje: "VASO",
        },
      },
      {
        code: "D052",
        title: "ALIMEN LACT FKDS VASO FRESAX150G",
        price: "1146",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "8",
        sub_categories: "8",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/D052.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "8",
          subcategoria: "8",
          sublinea: "8",
          linea: "8",
          embalaje: "VASO",
        },
      },
      {
        code: "D053",
        title: "ALIMEN LACT FKDS VASO MELOX150G",
        price: "1146",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "8",
        sub_categories: "8",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/D053.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "8",
          subcategoria: "8",
          sublinea: "8",
          linea: "8",
          embalaje: "VASO",
        },
      },
      {
        code: "D065",
        title: "ALIMEN LACT FKDS VASO MORAX150G",
        price: "1146",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "0",
        categories: "8",
        sub_categories: "8",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/D065.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "8",
          subcategoria: "8",
          sublinea: "8",
          linea: "8",
          embalaje: "VASO",
        },
      },
      {
        code: "D066",
        title: "ALIMEN LACT BOLSA MELOX850G",
        price: "4168",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "1",
        categories: "8",
        sub_categories: "8",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/D066.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "8",
          subcategoria: "8",
          sublinea: "8",
          linea: "8",
          embalaje: "BOLSA",
        },
      },
      {
        code: "D067",
        title: "ALIMEN LACT BOLSA MORAX850G",
        price: "4168",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "1",
        categories: "8",
        sub_categories: "8",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/D067.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "8",
          subcategoria: "8",
          sublinea: "8",
          linea: "8",
          embalaje: "BOLSA",
        },
      },
      {
        code: "D068",
        title: "ALIMEN LACT BOLSA FRESAX850G",
        price: "4168",
        unit: "UN",
        units: "UN",
        tax: "0",
        tax1: "0",
        tax2: "0",
        tax3: "0",
        combo: "false",
        weight: "1",
        categories: "8",
        sub_categories: "8",
        inventory: 1000,
        Packing_Unit: 0.0,
        imagen:
          "https://cw20storage.s3.amazonaws.com/1000/images/products/D068.png",
        presentation: {
          GM3: "",
          GM4: "",
          categoria: "8",
          subcategoria: "8",
          sublinea: "8",
          linea: "8",
          embalaje: "BOLSA",
        },
      },
    ],
    totalPage: 1,
    page: 1,
  },
};
const fakeProduct1 = fakeDataProducts.data.data[0];

export const fakeProductsSanity = fakeDataProducts.data.data.map((product) => {
  return {
    ...product,
    id: product.code,
    description: "",
    image: product.imagen,
    price: +product.price
  };
})

export const fakeProduct1Sanity = {
  ...fakeProduct1,
  id: fakeProduct1.code,
  description: "",
  image: fakeProduct1.imagen,
  price: +fakeProduct1.price
};
